### ISSUE TITLE
This Project Is In Haitus?

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [kolessios/insource-legacy#22]
title

**Comment by kolessios** [comment]
Unfortunately I think so. The limitations of Source Engine and its difficulty to implement new things in the free version have made me prefer to continue working with [Unity](https://unity3d.com/). Unless there is a massive interest from several people I think the project will be discontinued. Still, anyone can fork and continue the development.

**Comment by FriskTheFallenHuman** [comment]
well i making a port of the cancelled situation outbreak two the only thing that you can continue its finish up someone parts of the code, thus you can "expand" the engine using a method that the developer from Portal MP use "Detuors" detours was a little tool made by Microsoft to acces to functions compile in .dlls although this is a little tricky these developers made a change in the engine.dll to make it load goldsource maps has a explampe to see how it works, it works but due to naturally way its buggy but works, i hope you finish the missing parts of the coda, and this will became a god sdk base

**Comment by FriskTheFallenHuman** [comment]
maybe you can continue fixing this project because i like this project seriously
