### ISSUE TITLE
update the game's files whit the modified models of L4D2

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [kolessios/insource-legacy#3]
title

**Comment by kolessios** [comment]
I have already updated the [insource-games](https://github.com/WootsMX/insource-games) repository with the models for the players.

For the missing content just extract the _"models"_ and _"materials"_ folders from Left 4 Dead 2 in the root or in _"content/games/left4dead2"_

With that in theory you should be able to run the game without errors in the models.

Testing notes:
- When starting a map you start in spectator mode (ghost) you need to join a team with the command "**jointeam**".
2 = Humans
3 = Soldiers
4 = Infected (Incomplete)
- It is possible that several asserts appear when starting.
- To start the map "test_assault" correctly it is necessary to use the command "**exec start_assault_demo**"
- The file "fgd/apocalypse.fgd" will allow you to create maps with the new entities.
- The difficulty of the game is changed with the command "sv_difficulty"
1 = Easy
2 = Medium
3 = Hard
4 = Very Hard
5 = Ultra Hard
6 = Imposible/Realistic
