### ISSUE TITLE
[BUG] The "Ghost" mode dont seems to be a "Ghost"

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [kolessios/insource-legacy#6]
when you first join to a map the player don move also the player model is visible

**Comment by kolessios** [comment]
I think I've solved it, but I'm not sure:
https://github.com/WootsMX/insource/commit/dc9f1ade5b2dcdfee81d78cb79b18803fb9cf576#diff-8d66a1002126a3770a49c9755545b380
