### ISSUE TITLE
[BUG] Weapon Bob don't play on the pistol and play in other weapons when the player is idle

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [kolessios/insource-legacy#8]
title

**Comment by kolessios** [comment]
The viewmodel of L4D2 have a pose parameter called move_x in charge of doing this effect.

I have implemented it:
https://github.com/WootsMX/insource/commit/dc9f1ade5b2dcdfee81d78cb79b18803fb9cf576#diff-9c7907c978d0e5244d0a889ccc75184f

The pistol on the other hand does not have it... maybe it should be done manually, it seems strange to me.
